export const STACK_SIZES: Record<string, number> = {
  // 16 Stack Items
  BUCKET: 16,
  WATER_BUCKET: 16,
  LAVA_BUCKET: 16,
  MILK_BUCKET: 16,
  ENDER_PEARL: 16,
  EGG: 16,
  SNOWBALL: 16,
  HONEY_BOTTLE: 16,
  TURTLE_EGG: 16,
  ENDER_PEARL: 16,
  SNOWBALL: 16,
  EGG: 16,
  BUCKET: 16,
  WATER_BUCKET: 16,
  LAVA_BUCKET: 16,
  MILK_BUCKET: 16,
  SWEET_BERRIES: 64, // 64
  GLOW_BERRIES: 64, // 64
  SIGN: 16,
  OAK_SIGN: 16, SPRUCE_SIGN: 16, BIRCH_SIGN: 16, JUNGLE_SIGN: 16, ACACIA_SIGN: 16, DARK_OAK_SIGN: 16, MANGROVE_SIGN: 16, CHERRY_SIGN: 16, BAMBOO_SIGN: 16, CRIMSON_SIGN: 16, WARPED_SIGN: 16,
  WHITE_BANNER: 16, ORANGE_BANNER: 16, MAGENTA_BANNER: 16, LIGHT_BLUE_BANNER: 16, YELLOW_BANNER: 16, LIME_BANNER: 16, PINK_BANNER: 16, GRAY_BANNER: 16, LIGHT_GRAY_BANNER: 16, CYAN_BANNER: 16, PURPLE_BANNER: 16, BLUE_BANNER: 16, BROWN_BANNER: 16, GREEN_BANNER: 16, RED_BANNER: 16, BLACK_BANNER: 16,
};

// Default stack size is 64.
// Items that stack to 1:
const SINGLE_STACK = new Set([
  'IRON_SWORD', 'GOLDEN_SWORD', 'DIAMOND_SWORD', 'NETHERITE_SWORD', 'STONE_SWORD', 'WOODEN_SWORD',
  'IRON_PICKAXE', 'GOLDEN_PICKAXE', 'DIAMOND_PICKAXE', 'NETHERITE_PICKAXE', 'STONE_PICKAXE', 'WOODEN_PICKAXE',
  'IRON_AXE', 'GOLDEN_AXE', 'DIAMOND_AXE', 'NETHERITE_AXE', 'STONE_AXE', 'WOODEN_AXE',
  'IRON_SHOVEL', 'GOLDEN_SHOVEL', 'DIAMOND_SHOVEL', 'NETHERITE_SHOVEL', 'STONE_SHOVEL', 'WOODEN_SHOVEL',
  'IRON_HOE', 'GOLDEN_HOE', 'DIAMOND_HOE', 'NETHERITE_HOE', 'STONE_HOE', 'WOODEN_HOE',
  'IRON_HELMET', 'GOLDEN_HELMET', 'DIAMOND_HELMET', 'NETHERITE_HELMET', 'LEATHER_HELMET', 'CHAINMAIL_HELMET',
  'IRON_CHESTPLATE', 'GOLDEN_CHESTPLATE', 'DIAMOND_CHESTPLATE', 'NETHERITE_CHESTPLATE', 'LEATHER_CHESTPLATE', 'CHAINMAIL_CHESTPLATE',
  'IRON_LEGGINGS', 'GOLDEN_LEGGINGS', 'DIAMOND_LEGGINGS', 'NETHERITE_LEGGINGS', 'LEATHER_LEGGINGS', 'CHAINMAIL_LEGGINGS',
  'IRON_BOOTS', 'GOLDEN_BOOTS', 'DIAMOND_BOOTS', 'NETHERITE_BOOTS', 'LEATHER_BOOTS', 'CHAINMAIL_BOOTS',
  'POTION', 'SPLASH_POTION', 'LINGERING_POTION', 'MUSHROOM_STEW', 'RABBIT_STEW', 'SUSPICIOUS_STEW',
  'ENCHANTED_BOOK', 'WRITABLE_BOOK', 'WRITTEN_BOOK', 'MAP', 'FILLED_MAP',
  'SHEARS', 'FLINT_AND_STEEL', 'BOW', 'CROSSBOW', 'TRIDENT', 'ELYTRA', 'SHIELD', 'TOTEM_OF_UNDYING',
  'CAKE', 'BED', 'SADDLE', 'HORSE_ARMOR', 'IRON_HORSE_ARMOR', 'GOLDEN_HORSE_ARMOR', 'DIAMOND_HORSE_ARMOR',
  'LEATHER_HORSE_ARMOR', 'GOAT_HORN', 'MUSIC_DISC', 'DISC_FRAGMENT'
]);

export function getStackSize(type: string): number {
  if (STACK_SIZES[type]) return STACK_SIZES[type];
  if (SINGLE_STACK.has(type) || type.includes('SWORD') || type.includes('PICKAXE') || type.includes('AXE') || type.includes('SHOVEL') || type.includes('HOE') || type.includes('HELMET') || type.includes('CHESTPLATE') || type.includes('LEGGINGS') || type.includes('BOOTS') || type.includes('POTION') || type.includes('MUSIC_DISC')) return 1;
  return 64;
}
